/******************************************************************************
 * All typenames within m2 <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_TypeName_01$new 0,'TN_CatalogContainer_01', 'product catalogue container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Catalog_01', 'product catalogue', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_OrderContainer_01', 'order container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Order_01', 'order', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ShoppingCart_01', 'shopping cart', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Product_01', 'product', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Size_01', 'size', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Color_01', 'colour', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ShoppingCartLine_01', 'shopping cart entry', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductGroup_01', 'product group', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductSizeColorContainer_01', 'price container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductSizeColor_01', 'price', 'm2.store.StoreTypeConstants'
GO
EXEC p_TypeName_01$new 0,'TN_PaymentType_01', 'payment method', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PaymentTypeContainer_01', 'payment types container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_StateContainer_01', 'workflow state container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductProfile_01', 'product profile', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductProfileContainer_01', 'product profile container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductGroupProfileContainer_01', 'product group profile container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductGroupProfile_01', 'product group profile', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductBrand_01', 'product brand', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductBrandContainer_01', 'product brand container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductCollection_01', 'product assortment', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductCollectionContainer_01', 'product assortment container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductProperties_01', 'product key', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_ProductPropertiesContainer_01', 'product key container', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PropertyCategory_01', 'product key category', 'm2.store.StoreTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PropertyCategoryContainer_01', 'product key category container', 'm2.store.StoreTypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
