/******************************************************************************
 * All objectdescs within m2 <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.1 2010/04/15 10:38:38 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_ObjectDesc_01$new 0,'OD_tabTemplates', 'templates', 'All templates for market trades.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domDiscussions', 'discussions', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domDiscM2', 'm2', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domDiscProjects', 'projects', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domDiscInfoTips', 'information + tips', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domDiscOffers', 'offer + buy', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabDiscussion', 'discussion', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabDiscussions', 'discussions', '', 'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
