/******************************************************************************
 * All objectdescs within m2 <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.1 2010/04/15 10:38:38 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_ObjectDesc_01$new 0,'OD_tabProperties', 'properties', 'Properties of an item.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabPrices', 'prices', 'Size/color/prices, price graduation, further properties on which the price depends.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabAssortments', 'assortments', 'Assortments for this product.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabProductSources', 'product sources', 'Product source verification.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabBillAddress', 'invoice address', 'Address of member to which the bill should be sent.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatalogManagement', 'catalog administration', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatProductBrands', 'product brands', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatProductKeyCategories', 'product key categories', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatProductKeys', 'product keys', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatProductGroupProfiles', 'product group profiles', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domCatProductProfiles', 'product profiles', '', 'ibs.bo.ObjectDesc'
GO
EXEC p_ObjectDesc_01$new 0,'OD_domProducts', 'item offers', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domProdLeaflets', 'leaflet', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domProdSupplier1', 'supplier 1', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domProdSourceEvidence', 'source verification', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_wspShoppingCart', 'shopping cart', 'Click on oders or delete list to change.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_wspOrders', 'orders', 'overview about orders', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabCatalog', 'catalogue', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabShoppingCart', 'shopping cart', 'Shopping cart of the actual user.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_paymentsTypeContainer', 'paymenttype', 'possibly paymenttypes in the system', 'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
