/******************************************************************************
 * All typenames within the framework. <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_TypeName_01$new 0,'TN_File_01', 'file', 'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,'TN_Url_01', 'hyperlink', 'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,'TN_Attachment_01', 'attachment', 'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,'TN_AttachmentContainer_01', 'attachment container', 'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,'TN_Note_01', 'note', 'ibs.bo.type.TypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
