/******************************************************************************
 * The IBS_OBJECT table incl. indexes. <BR>
 * 
 *
 * @version     1.10.0001, 04.08.1999
 *
 * @author      Christine Keim (CK)  990804
 ******************************************************************************
 */

CREATE SEQUENCE objectIdSeq
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 20;
	

CREATE TABLE /*USER*/IBS_OBJECT
(
    ID NUMBER (10, 0) NOT NULL,
    OID RAW (8) NOT NULL,
    STATE NUMBER (10, 0) NOT NULL,
    TVERSIONID NUMBER (10, 0) NOT NULL,
    TYPENAME VARCHAR2 (63) NOT NULL,
    ISCONTAINER NUMBER (1, 0) NOT NULL,
    NAME VARCHAR2 (63) NOT NULL,
    CONTAINERID RAW (8) NOT NULL,
    CONTAINERKIND NUMBER (10, 0) NOT NULL,
    ISLINK NUMBER (1, 0),
    LINKEDOBJECTID RAW (8) NOT NULL,
    SHOWINMENU NUMBER (1, 0)  ,
    FLAGS NUMBER (10, 0) NOT NULL,
    OWNER NUMBER (10, 0) NOT NULL,
    OLEVEL NUMBER (10, 0) NOT NULL,
    POSNO NUMBER (10, 0) NOT NULL,
    POSNOPATH VARCHAR2 (254) NOT NULL,
    CREATIONDATE DATE NOT NULL,
    CREATOR NUMBER (10, 0) NOT NULL,
    LASTCHANGED DATE NOT NULL,
    CHANGER NUMBER(10, 0) NOT NULL,
    VALIDUNTIL DATE,
    DESCRIPTION VARCHAR2 (255),
    ICON VARCHAR2 (63),
    PROCESSSTATE NUMBER (10, 0), 
    RKEY NUMBER (10, 0),
    consistsOfId NUMBER (10, 0) NOT NULL    -- unique tab id if the object
                                            -- represents a tab
) /*TABLESPACE*/;

ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (id DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (oid DEFAULT hexToRaw ('0000000000000000'));
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (state DEFAULT 2);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (tVersionId DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (typeName DEFAULT 'UNKNOWN');
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (isContainer DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (containerId DEFAULT hexToRaw ('0000000000000000'));
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (isLink DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (linkedObjectId DEFAULT hexToRaw ('0000000000000000'));
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (showInMenu DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (flags DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (owner DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (oLevel DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (posNo DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (posNoPath DEFAULT '0000');
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (creationDate DEFAULT SYSDATE);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (creator DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (lastChanged DEFAULT SYSDATE);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (changer DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (rKey DEFAULT 0);
ALTER TABLE /*USER*/IBS_OBJECT  MODIFY (consistsOfId DEFAULT 0);

exit;
