/******************************************************************************
 * All objectdescs within m2 <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.1 2010/04/15 10:38:38 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_ObjectDesc_01$new 0,'OD_tabContacts', 'contacts', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabAddress', 'address', 'Address.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabBranches', 'branches', 'This container contains the branches of the member.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domMasterData', 'master data', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domMadSuppliers', 'suppliers', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domMadMembers', 'members', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_domMadPartners', 'partners', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabMasterdata', 'master data', '', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabPersonUsers', 'users', 'The users which are assigned to this person.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabPersons', 'persons', '', 'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
