/******************************************************************************
 * All objectdescs within m2 <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.1 2010/04/15 10:38:38 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO


GO
-- show count messages again:
SET NOCOUNT OFF
GO
