/******************************************************************************
 * All typenames within m2 <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_TypeName_01$new 0,'TN_Discussion_01', 'discussion', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Thread_01', 'topic', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Article_01', 'contribution', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_NewsContainer_01', 'news', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_DiscussionContainer_01', 'discussion container', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_BlackBoard_01', 'bulletin board', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_XMLDiscussionTemplate_01', 'trade market template', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_XMLDiscussion_01', 'trade market', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_DiscXMLViewer_01', 'trade market entry', 'm2.bbd.BbdTypeConstants'
EXEC p_TypeName_01$new 0,'TN_XMLDiscussionTemplateContainer_01', 'trade market templates', 'm2.bbd.BbdTypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
