/******************************************************************************
 * All typenames within m2 <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_TypeName_01$new 0,'TN_MasterDataContainer_01', 'master data container', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Person_01', 'person', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PersonContainer_01', 'person container', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Company_01', 'company', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_Address_01', 'address', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_SelectUserContainer_01', 'user selection container', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_SelectCompanyContainer_01', 'company selection container', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PersonUserContainer_01', 'person user container', 'm2.mad.MadTypeConstants'
EXEC p_TypeName_01$new 0,'TN_PersonSearchContainer_01', 'person search container', 'm2.mad.MadTypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
