/******************************************************************************
 * All typenames within m2 <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_TypeName_01$new 0,'TN_Document_01', 'document', 'm2.doc.DocTypeConstants'
EXEC p_TypeName_01$new 0,'TN_DocumentContainer_01', 'document container', 'm2.doc.DocTypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
