/******************************************************************************
 * All objectdescs within the framework. <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.1 2010/04/15 10:38:38 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_ObjectDesc_01$new 0,'OD_tabAttachments', 'attachments', 'Attachments for the object.', 'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,'OD_tabAttachmentContainer', 'attachment container', 'attachment container', 'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
