/******************************************************************************
 * All objectdescs within the framework. <BR>
 *
 * @version     $Id: U300001v_createObjectDesc.sql,v 1.2 2010/05/04 16:22:17 btatzmann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

EXEC p_ObjectDesc_01$new 0,N'OD_domLocales', N'locales', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLocaleEnUS', N'en_US', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLocaleDeAT', N'de_AT', N'', N'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
