/******************************************************************************
 * All objectdescs within the framework. <BR>
 *
 * @version     $Id: createObjectDesc.sql,v 1.3 2010/05/03 13:56:38 btatzmann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

delete ibs_objectdesc_01

EXEC p_ObjectDesc_01$new 0,N'OD_tabReferences', N'links', N'References to other information.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabRights', N'rights', N'Permissions for the object.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabProtocol', N'log', N'Object log.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabMembership', N'membership in', N'Groups in which the user is a member.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabAttachments', N'attachments', N'Attachments for the object.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabRecipients', N'recipients', N'List of recipients.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabContainership', N'contains', N'Types which can be contained within the type.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabVersions', N'versions', N'Versions of a type.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabParameters', N'parameters', N'The methods parameters.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabGroups', N'groups', N'All groups in which the user is member.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabButtons', N'buttons', N'The tabs buttons.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabAttributes', N'attributes', N'The type versions attributes.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabMethods', N'methods', N'The type versions methods.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabTabs', N'tabs', N'The type versions tabs.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysAdmin', N'Admin', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysRoot', N'system root', N'', N'ibs.bo.ObjectDesc'
GO
EXEC p_ObjectDesc_01$new 0,N'OD_sysRootRef', N'system root', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysDataInterchange', N'data interchange', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysDIImport', N'import', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysDIExport', N'export', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysLayouts', N'layouts', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysLayoutStandard', N'standard', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysDomainSchemes', N'domain schemes', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_sysAdminUserprofile', N'user profile', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domAdmin', N'Administrator', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domDomain', N'domain', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domPublic', N'#CONFVAR.ibsbase.menuPublic#', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domUserMmt', N'user administration', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domGroups', N'groups', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domUsers', N'users', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domGroupAll', N'all', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domGroupAdministrators', N'administrators', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domGroupUserGroupAdmins', N'user administrators', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domGroupStructAdmins', N'struct administrators', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domWorkspaces', N'workspaces', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLocales', N'locales', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLocaleEnUS', N'en_US', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLocaleDeAT', N'de_AT', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLayouts', N'layouts', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domLayoutStandard', N'standard', N'', N'ibs.bo.ObjectDesc'
GO
EXEC p_ObjectDesc_01$new 0,N'OD_domDataInterchange', N'data interchange', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domDIImport', N'import', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domDIExport', N'export', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domNews', N'news', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInformation', N'information', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoCommon', N'common', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoPress', N'press', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoArticles', N'articles', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoForms', N'forms', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoSideGlances', N'side glances', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domInfoTrendInfo', N'trend information', N'', N'ibs.bo.ObjectDesc'
GO
EXEC p_ObjectDesc_01$new 0,N'OD_domProjects', N'projects', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_domProjM2', N'm2', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspPrivate', N'#CONFVAR.ibsbase.menuPrivate#', N'private workspace', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspWorkBox', N'workbox', N'Here you can create items of your interest', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspNews', N'news', N'Items, which were added until a specific date (=>Userprofile)', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspHotList', N'hotlist', N'Important objects which are often used', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspOutBox', N'outbox', N'contains all sent objects', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspInBox', N'inbox', N'contains all objects recieved from others', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspProfile', N'user profile', N'All data to customize the workspace layout.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_queryAllTypes', N'all types', N'all types', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_wspWasteBasket', N'wastebasket', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabAddressValues', N'address data', N'Address data of the user.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabContainer', N'container', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabContent', N'content', N'Content of the container.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabContentFrameset', N'content', N'Content of the container.', N'ibs.bo.ObjectDesc'
GO
EXEC p_ObjectDesc_01$new 0,N'OD_tabFilter', N'filter', N'', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabInfo', N'information', N'Common object info.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabInfoFrameset', N'information', N'Common object info.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabMayContain', N'may contain', N'Types which may be contained within objects of this type.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabPrivate', N'#CONFVAR.ibsbase.menuPrivate#', N'The private container of the user.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabForm', N'form', N'Miscellaneous form information.', N'ibs.bo.ObjectDesc'
EXEC p_ObjectDesc_01$new 0,N'OD_tabForms', N'forms', N'Room for adding forms.', N'ibs.bo.ObjectDesc'

GO
-- show count messages again:
SET NOCOUNT OFF
GO
