/******************************************************************************
 * All typenames within the framework. <BR>
 *
 * @version     $Id: createTypeNames.sql,v 1.1 2010/04/15 10:40:54 rburgermann Exp $
 *
 * @author      autogenerated by m2 MultiLang
 ******************************************************************************
 */

-- don't show count messages:
SET NOCOUNT ON
GO

delete ibs_typename_01
GO

EXEC p_TypeName_01$new 0,N'TN_SentObject_01', N'outbox item', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Type_01', N'type', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TypeContainer_01', N'type container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Method_01', N'method', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_MethodContainer_01', N'method container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Parameter_01', N'parameter', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ParameterContainer_01', N'parameter container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Inbox_01', N'inbox', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Workspace_01', N'workspace', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_GroupContainer_01', N'group container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_UserContainer_01', N'user container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_UserGroupsContainer_01', N'user groups container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_UserAdminContainer_01', N'user administration', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_UserProfile_01', N'user profile', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Tab_01', N'tab', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TabContainer_01', N'container tab', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Button_01', N'button', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ButtonContainer_01', N'button container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TVersion_01', N'type version', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TVersionContainer_01', N'type version container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_RoleContainer_01', N'role container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TabObject_01', N'object tab', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TabView_01', N'view tab', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_MemberShip_01', N'membership container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Root_01', N'system root', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_TypeReference_01', N'type reference', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TypeReferenceContainer_01', N'type reference container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_CleanContainer_01', N'clean list container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ReceivedObject_01', N'inbox item', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_LogContainer_01', N'log container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_LayoutContainer_01', N'layout container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Layout_01', N'layout', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Integrator_01', N'integrator', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ObjectSearchContainer_01', N'object search container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_IntegratorContainer_01', N'data interchange', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ImportScript_01', N'import script', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ImportScriptContainer_01', N'import script container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Connector_01', N'connector', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ConnectorContainer_01', N'connector container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Translator_01', N'translator', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_TranslatorContainer_01', N'translator container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_XMLViewer_01', N'form', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_ImportContainer_01', N'import container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ExportContainer_01', N'export container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_DocumentTemplate_01', N'form template', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_DocumentTemplateContainer_01', N'form template container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_XMLViewerContainer_01', N'form container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_HelpContainer_01', N'help container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Help_01', N'help', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_HTTPConnector_01', N'HTTP connector', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_EDISwitchConnector_01', N'EDI switch connector', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_HTTPScriptConnector_01', N'CGI-script connector', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_DomainSchemeContainer_01', N'domain scheme container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_DomainScheme_01', N'domain scheme', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_FileConnector_01', N'file connector', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_FTPConnector_01', N'FTP connector', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_MailConnector_01', N'e-mail connector', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_SimpleSearchContainer_01', N'simple search container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_QueryCreator_01', N'query creator', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_QueryCreatorContainer_01', N'query creator container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_QueryExecutive_01', N'query', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_NOTYPE', N'', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_BusinessObject', N'business object', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Container', N'container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Referenz_01', N'reference', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ReferenzContainer_01', N'reference container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Menu_01', N'menu', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_MenuElement_01', N'menu item', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_SearchContainer_01', N'search container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_User_01', N'user', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Group_01', N'group', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Rights_01', N'rights', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_RightsContainer_01', N'rights container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Domain_01', N'domain', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_RecipientContainer_01', N'recipient container', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_Recipient_01', N'recipient', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_SentObjectContainer_01', N'outbox', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_ServicePoint_01', N'service point', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_WasteBasket_01', N'wastebasket', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_UserAddress_01', N'Addressvalues', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_SAPBCXMLRFCConnector_01', N'SAP XMLRFC connector', N'ibs.bo.type.TypeConstants'
GO
EXEC p_TypeName_01$new 0,N'TN_ASCIITranslator_01', N'ASCII to XML Translator', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_DBQueryCreator_01', N'DBQueryCreator', N'ibs.bo.type.TypeConstants'
EXEC p_TypeName_01$new 0,N'TN_NewsContainer_01', N'news', N'ibs.bo.type.TypeConstants'
GO

-- show count messages again:
SET NOCOUNT OFF
GO
